name: aloqa_nazorati
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #packages
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  flutter_svg: ^1.1.0
  shared_preferences: ^2.0.13
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  file_picker: ^4.5.1
  file_saver: ^0.1.1
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.2
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.0.9
  equatable: ^2.0.3
  get_it: ^7.2.0
  path_provider: ^2.0.11
  downloads_path_provider_28: ^0.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.1.10
  permission_handler: ^10.0.0
  flutter_downloader: ^1.8.3+2
  dio: ^4.0.6
  camera: ^0.10.0+1
  image_picker: ^0.8.5+3
  

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
     - assets/
     - assets/images/
     - assets/icons/


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/bold.ttf
          weight: 700
        - asset: fonts/regular.ttf
          weight: 400
        - asset: fonts/medium.ttf
          weight: 500
        - asset: fonts/light.ttf
          weight: 300

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
